[book]
authors = ["matchy233"]
language = "en"
multilingual = false
src = "src"
title = "Notes @ ETH Zürich"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
mathjax-support = true

[output.html.fold]
enable = true
level = 0

# [preprocessor.pytoc]
# command = "python3 scripts/autogen-toc.py"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.toc]
command = "mdbook-toc"
renderers = ["html"]
