[book]
authors = ["matchy233"]
language = "en"
multilingual = false
src = "src"
title = "Notes @ ETH Zürich"


[output.wordcount]
optional = true

[output.katex]

[output.html]
mathjax-support = true

[output.html.fold]
enable = true
level = 0

[preprocessor.katex]
renderers = ["html"]
