[book]
authors = ["matchy233"]
language = "en"
multilingual = true
src = "src"
title = "Notes @ ETH Zürich"

[output.html]
mathjax-support = true
default-theme = "Rust"
preferred-dark-theme = "Ayu"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
additional-css = ["theme/custom.css"]

[output.html.fold]
enable = true
level = 0

[output.pytoc]
command = "python3 ../../scripts/autogen-toc.py"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.toc]
command = "mdbook-toc"
renderers = ["html"]
